catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - theme
  - demo

overrides:
  chokidar: 4.0.1
  semver: ^7

catalog:
  '@antfu/eslint-config': ^7.7.3
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.78
  '@unocss/eslint-plugin': ^66.6.8
  bumpp: ^11.0.1
  eslint: ^10.2.1
  eslint-plugin-format: ^1.1.0
  typescript: ^5.9.3
  valaxy: ^0.28.5
  vitest: ^4.1.4
  vue-tsc: 2.2.0
packageExtensions:
  valaxy:
    dependencies:
      nanoid: ^5.1.9
